apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: partner-frontend
  name: partner-frontend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: partner-frontend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: deploy-on-openshift
      uri: https://github.com/mgohashi/partner-frontend.git
#    contextDir: "dist"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:1.12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: IhqI7W_dsDcQlkNCfml1
    type: GitHub
  - generic:
      secret: 0NPvN8SbXM_Q6b-jyZYj
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
